### ISSUE TITLE
Unable to connect to InfluxDB if battery.volate.nominal changed from default

### ISSUE THREAD

**Issue by agit22** [mihai-cindea/nut-influxdb-exporter#5]
Due to a quirk with how the UPS shows battery voltage in NUT I've added an extra parameter on the NUT server, override.battery.voltage.nominal = 12 and override.battery.packs = 2.

With these changes I'm no longer able to export to InfluxDB

Here's the log

```
[DEBUG] list_vars called...
[{'measurement': 'ups_status', 'fields': {'battery.charge': 100,
 'battery.packs': 2, 'battery.runtime': 1020, 'battery.voltage': 13.7, 'battery.voltage.high': 13.0, 'battery.voltage.low': 10.4,
 'battery.voltage.nominal': 12,
 'driver.parameter.chargetime': 14400, 'driver.parameter.pollinterval': 2, 'driver.parameter.port': 'auto',
 'driver.parameter.runtimecal': '102,100,300,50', 'driver.parameter.synchronous': 'no', 'input.current.nominal': 7.0, 'input.frequency': 50.1,
 'input.frequency.nominal': 50, 'input.voltage': 228.7, 'input.voltage.fault': 228.7,
 'input.voltage.nominal': 230, 'output.voltage': 228.7,
 'ups.delay.shutdown': 30, 'ups.delay.start': 180, 'ups.load': 14,
 'ups.status': 'OL', 'ups.type': 'offline / line interactive',
 'watts': 168.0},
 'tags': {'host': 'power', 'device.type': 'ups', 'driver.version': '2.7.4', 'ups.productid': '5161', 'ups.vendorid': '0665'}}]

[DEBUG] http://10.0.0.44:8086 "POST /write?db=nutty HTTP/1.1" 400 174
Traceback (most recent call last):
File "/src/nut-influxdb-exporter.py", line 112, in <module>
print(client.write_points(json_body))
File "/usr/local/lib/python3.7/site-packages/influxdb/client.py", line 530, in write_points
consistency=consistency)
File "/usr/local/lib/python3.7/site-packages/influxdb/client.py", line 598, in _write_points
protocol=protocol
File "/usr/local/lib/python3.7/site-packages/influxdb/client.py", line 343, in write
headers=headers
File "/usr/local/lib/python3.7/site-packages/influxdb/client.py", line 302, in request
raise InfluxDBClientError(response.content, response.status_code)
influxdb.exceptions.InfluxDBClientError: 400: {"error":"partial write: field type conflict: input field
\"battery.voltage.nominal\" on measurement \"ups_status\" is type integer, already exists as type float dropped=1"
```

**Comment by mcindea** [comment]
I think this is more of a InfluxDB issue and you need to change those field types in InfluxDB. I'm not super familiar with it, but probably the easiest would be to just give float values instead of integers, if you have control over that, of course.
```
override.battery.voltage.nominal = 12.0
override.battery.packs = 2.0
```

Another solution would be to simply drop the db and start a new one, and the values will be automatically created to integer instead of floats, but then you will loose the historical data. Of course you can then just re-import the historical data with that value changed.

Another one would be if those values are static, as if they never change, you can declare them as tags in `tag_keys` and that way the type won't matter. These however are not considered metrics, and I'm not sure how that impacts your graphs. Though i think this will also require a rewrite of the table: https://community.influxdata.com/t/convert-field-to-tag/913

**Comment by mcindea** [comment]
Did this work for you?

**Comment by mcindea** [comment]
Closing issue, feel free to reopen if it's still an issue for you.
