### ISSUE TITLE
Error Getting Data from NUT

### ISSUE THREAD

**Issue by wranglatang** [mihai-cindea/nut-influxdb-exporter#8]
Been getting the below error in my log every once in a while. Seems like it disconnects and struggles to reconnect again. Would be good to have this fixed or have the docker restart so that it can try and reconnect again.

```
Connecting to InfluxDB host:10.168.40.1, DB:nut
Connected successfully to InfluxDB
Connecting to NUT host 10.168.40.1:3493
Connected successfully to NUT
Error getting data from NUT

Error connecting to InfluxDB.

Error getting data from NUT

Error getting data from NUT

Error getting data from NUT

Error getting data from NUT

Error getting data from NUT
```

**Comment by mcindea** [comment]
Interesting, I thought i fixed this a while back.
Is this still an issue? Do you have an average time after it gets disconnected? I could make it connect every X reports.

**Comment by mcindea** [comment]
So I updated the python code now so whenever it gets an error while connecting to NUT or InfluxDB it will just re-execute the python script so it should try reconnecting. 

Can you try and see if you still have this issue?

**Comment by imascarenhas** [comment]
I had this issue too, and it looks like it was due to the renaming of the UPS_ALIAS environment variable.

The last release introduced a breaking change if you use Docker or using environment variable for configuration which requires you to change the UPS_ALIAS environment variable to UPS_NAME. Once I did this it continued to work as before.
